version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies..."
      - yum install -y unzip wget
      - echo "Installing Terraform..."
      - wget https://releases.hashicorp.com/terraform/1.5.7/terraform_1.5.7_linux_amd64.zip
      - unzip terraform_1.5.7_linux_amd64.zip
      - mv terraform /usr/local/bin/
      - terraform version

  pre_build:
    commands:
      - echo "Initializing Terraform..."
      - cd terraform
      - terraform init -input=false
      - terraform validate

  build:
    commands:
      - echo "Planning Terraform changes..."
      - terraform plan -out=tfplan

artifacts:
  files:
    - terraform/tfplan
    - terraform/*.tfstate
    - terraform/*.tfstate.backup
