version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - wget https://releases.hashicorp.com/terraform/1.5.7/terraform_1.5.7_linux_amd64.zip
      - unzip terraform_1.5.7_linux_amd64.zip
      - mv terraform /usr/local/bin/
  pre_build:
    commands:
      - cd terraform
      - terraform init
  build:
    commands:
      - terraform destroy -auto-approve