version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - yum update -y
      - yum install -y wget unzip
      - echo "Installing Terraform..."
      - wget -q https://releases.hashicorp.com/terraform/1.5.7/terraform_1.5.7_linux_amd64.zip -O terraform.zip
      - unzip -o terraform.zip
      - mv terraform /usr/local/bin/
      - terraform version

  pre_build:
    commands:
      - echo "Initializing Terraform..."
      - cd terraform
      - terraform init -input=false
      - terraform validate

  build:
    commands:
      - echo "Planning Terraform changes..."
      - terraform plan -out=tfplan

artifacts:
  files:
    - terraform/tfplan
    - terraform/*.tfstate
    - terraform/*.tfstate.backup
